{
 "title": "MediFlow Dashboard",
 "panels": [
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "RPS" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"5..\"}[1m])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "Active" }
   ]
  }
 ]
}